services:
  app:
    image: nginx:alpine
    container_name: app
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    expose:
      - "80"
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-network
      traefik.http.routers.app.rule: "Host(`app.kktree.cn`)"
      traefik.http.routers.app.entrypoints: websecure
      traefik.http.routers.app.tls: "true"
      traefik.http.routers.app.tls.certresolver: myresolver
      traefik.http.services.app.loadbalancer.server.port: 80
    networks:
      - traefik-network
      - app-network

networks:
  traefik-network:
    external: true
  app-network: